// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hqwujtzlhwycndpfqjvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxd3VqdHpsaHd5Y25kcGZxanZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNDE0MjYsImV4cCI6MjA3NTYxNzQyNn0.hamdd1-gM1ekEwPwNMWiWJApCYDGukbDyCyPxiqYOL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);